version: "2"
services:
  server:
    build: ./docker-src
    image: netlifedesign/craft-starter-base
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/html/
      - ./storage/:/var/www/html/storage/:delegated
      - ./docker-src/src/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_URL=mysql://root:somegloriouspassword@database:3306/craft_cms
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
  database:
    image: mysql:8
    ports:
      - "4306:3306"
    volumes:
      - ./docker-src/db-config:/etc/mysql/conf.d:cached
      - ./docker-src/db-dump:/docker-entrypoint-initdb.d:cached
    environment:
      - MYSQL_ROOT_PASSWORD=somegloriouspassword
      - MYSQL_DATABASE=craft_cms
    cap_add:
      - SYS_NICE
  
